#ifndef _A2WIDGETIDENTIFIERS_H_
#define _A2WIDGETIDENTIFIERS_H_

/*
 * The Component class takes a string that serves as a unique
 * identifier for that Component. You should use the following
 * identifiers for the Components for your assignment. See the
 * assignment spec for more information.
 */
#define MAIN_PANEL_ID "MAIN_PANEL_ID"

#define TURTLE_GRAPHICS_PANEL_ID "TURTLE_GRAPHICS_PANEL_ID"
#define TURTLE_GRAPHICS_OUTPUT_LABEL_ID "TURTLE_GRAPHICS_OUTPUT_LABEL_ID"
#define TURTLE_GRAPHICS_WIDGET_ID "TURTLE_GRAPHICS_WIDGET_ID"
#define TURTLE_GRAPHICS_LABEL_ID "TURTLE_GRAPHICS_LABEL_ID"

#define PLAYBACK_PANEL_ID "PLAYBACK_PANEL_ID"
#define PLAYBACK_OUTPUT_LABEL_ID "PLAYBACK_OUTPUT_LABEL_ID"
#define PLAYBACK_SLIDER_ID "PLAYBACK_SLIDER_ID"

#define CURRENT_TURTLE_STEP_PANEL_ID "CURRENT_TURTLE_STEP_PANEL_ID"
#define CURRENT_TURTLE_STEP_LABEL_ID "CURRENT_TURTLE_STEP_LABEL_ID"
#define CURRENT_TURTLE_STEP_SLIDER_ID "CURRENT_TURTLE_STEP_SLIDER_ID"

#define BUTTON_PANEL_ID "BUTTON_PANEL_ID"
#define GO_TO_START_BUTTON_ID "GO_TO_START_BUTTON_ID"
#define PREVIOUS_FRAME_BUTTON_ID "PREVIOUS_FRAME_BUTTON_ID"
#define PLAY_BUTTON_ID "PLAY_BUTTON_ID"
#define NEXT_FRAME_BUTTON_ID "NEXT_FRAME_BUTTON_ID"
#define GO_TO_END_BUTTON_ID "GO_TO_END_BUTTON_ID"

#endif /* _A2WIDGETIDENTIFIERS_H_ */
